load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "mod",
    srcs = ["mod.go"],
    importpath = "github.com/arkeros/senku/bazel/pkg/mod",
    visibility = ["//visibility:public"],
)
