"""Pinned provider hashes for the terraform module extension.

Generated by `//devtools/build/tools/tf/providers:repin`. **Do not edit
by hand** — bump versions in `bazel/include/terraform.MODULE.bazel`,
then run the pin tool.

Each entry maps `<source>@<version>` to a per-platform dict of
hashes. `sha256` is the hex-encoded sha256 of the provider zip,
consumed by `download_and_extract` for the bazel-side download
integrity check. `h1` is terraform's directory-hash format
(base64 of sha256 over the unpacked-file manifest, `golang.org/x/mod
/sumdb/dirhash` Hash1) and goes verbatim into the generated
`.terraform.lock.hcl`.
"""

PROVIDER_HASHES = {
    "hashicorp/google@7.29.0": {
        "darwin_amd64": {
            "sha256": "2afdb8530b53edb1ea39aa3736e0a28eb8413d042296e01026c027e3b5abf12f",
            "h1": "h1:aKrtVbk3naU8dxw5phrOK2PtN02dPkBV/3+3eAl36TU=",
        },
        "darwin_arm64": {
            "sha256": "2b920672181a115a72c901a0f121b4a5425d9977b05c0231e84a669f3c8ac731",
            "h1": "h1:SQaFVC55GTev4MsXkmyFWTtH0OhyJXGV7Txi6ZguLsc=",
        },
        "linux_amd64": {
            "sha256": "3996360bf8f3a17819183df69fc6dad750e8661cbf8f24b1ef96f2db5632f92d",
            "h1": "h1:o0puBmN8n9phQ3SK5z5dcjRCn7fL48rqSKduDv5QbiE=",
        },
        "linux_arm64": {
            "sha256": "207a6de17871088d907bf11854419fbc9793fa832f4bbdcc1aa0d63d18f87dcf",
            "h1": "h1:gEx4zyCsc4WwhuSViF3H90jXdp/qePjClyEoW7vjFVI=",
        },
    },
    "hashicorp/kubernetes@2.38.0": {
        "darwin_amd64": {
            "sha256": "5136e51765d6a0b9e4dbcc3b38821e9736bd2136cf15e9aac11668f22db117d2",
            "h1": "h1:7nJdsd1RMPBtOjDXidB37+KSDN5VcOWkbkow69qJVGc=",
        },
        "darwin_arm64": {
            "sha256": "1be998e67206f7cfc4ffe77c01a09ac91ce725de0abaec9030b22c0a832af44f",
            "h1": "h1:soK8Lt0SZ6dB+HsypFRDzuX/npqlMU6M0fvyaR1yW0k=",
        },
        "linux_amd64": {
            "sha256": "d39861aa21077f1bc899bc53e7233262e530ba8a3a2d737449b100daeb303e4d",
            "h1": "h1:5CkveFo5ynsLdzKk+Kv+r7+U9rMrNjfZPT3a0N/fhgE=",
        },
        "linux_arm64": {
            "sha256": "63fab47349852d7802fb032e4f2b6a101ee1ce34b62557a9ad0f0f0f5b6ecfdc",
            "h1": "h1:XCkL/mxjWTawg6gg+jlpCQhF/+SNRoCEZxbbkDTj42s=",
        },
    },
}
