"""Pinned provider hashes for the terraform module extension.

Generated by `//devtools/build/tools/tf/providers:repin`. **Do not edit
by hand** — bump versions in `bazel/include/terraform.MODULE.bazel`,
then run the pin tool.

Each entry maps `<source>@<version>` to a per-platform dict of
hashes. `sha256` is the hex-encoded sha256 of the provider zip,
consumed by `download_and_extract` for the bazel-side download
integrity check. `h1` is terraform's directory-hash format
(base64 of sha256 over the unpacked-file manifest, `golang.org/x/mod
/sumdb/dirhash` Hash1) and goes verbatim into the generated
`.terraform.lock.hcl`.
"""

PROVIDER_HASHES = {
    "hashicorp/google@7.29.0": {
        "darwin_amd64": {
            "sha256": "2afdb8530b53edb1ea39aa3736e0a28eb8413d042296e01026c027e3b5abf12f",
            "h1": "h1:aKrtVbk3naU8dxw5phrOK2PtN02dPkBV/3+3eAl36TU=",
        },
        "darwin_arm64": {
            "sha256": "2b920672181a115a72c901a0f121b4a5425d9977b05c0231e84a669f3c8ac731",
            "h1": "h1:SQaFVC55GTev4MsXkmyFWTtH0OhyJXGV7Txi6ZguLsc=",
        },
        "linux_amd64": {
            "sha256": "3996360bf8f3a17819183df69fc6dad750e8661cbf8f24b1ef96f2db5632f92d",
            "h1": "h1:o0puBmN8n9phQ3SK5z5dcjRCn7fL48rqSKduDv5QbiE=",
        },
        "linux_arm64": {
            "sha256": "207a6de17871088d907bf11854419fbc9793fa832f4bbdcc1aa0d63d18f87dcf",
            "h1": "h1:gEx4zyCsc4WwhuSViF3H90jXdp/qePjClyEoW7vjFVI=",
        },
    },
}
