load("//devtools/build/icons:icons.bzl", "app_icons")

app_icons(
    name = "icons",
    app_name = "Mesa para dos",
    background_color = "#0E1A17",
    short_name = "Mesa",
    svg = "icon.svg",
    theme_color = "#0E1A17",
    visibility = ["//apps/table-for-two:__pkg__"],
)
