"""Aspects that enforce policy on the OCI build graph.

`mirror_push_enforcement_aspect` fails analysis when a raw `image_push` rule
targets the public mirror surface (`ghcr.io/arkeros/senku/*`) without going
through the `mirror_push` macro. This is the build-graph-level enforcement
of ADR 0006's "every mirror image is signed and attested" policy: there is
no syntactically valid way to push to the mirror prefix that bypasses sign
and attest, because the aspect catches you at analysis time.

Wired in `.bazelrc` via `common --aspects=...` so it runs on every build.
The `mirror_push_managed` tag on rules generated by `mirror_push` is the
opt-in marker the aspect looks for.
"""

load("//oci:config.bzl", "OCI_REGISTRY", "OCI_REPOSITORY_PREFIX")

_MIRROR_PUSH_MANAGED_TAG = "mirror_push_managed"

def _mirror_push_enforcement_impl(target, ctx):
    if ctx.rule.kind != "image_push":
        return []

    registry = getattr(ctx.rule.attr, "registry", "")
    repository = getattr(ctx.rule.attr, "repository", "")
    tags = getattr(ctx.rule.attr, "tags", []) or []

    is_mirror_prefix = (
        registry == OCI_REGISTRY and
        repository.startswith(OCI_REPOSITORY_PREFIX + "/")
    )
    is_managed = _MIRROR_PUSH_MANAGED_TAG in tags

    if is_mirror_prefix and not is_managed:
        fail((
            "{label}: raw `image_push` to the public mirror surface " +
            "({registry}/{repository}) is not allowed. Use `mirror_push` " +
            "from `//oci:mirror_push.bzl` so the image is signed and " +
            "SLSA-attested. See ADR 0006 " +
            "(`docs/adr/0006-bazel-native-cosign-mirror-signing.md`)."
        ).format(
            label = target.label,
            registry = registry,
            repository = repository,
        ))

    return []

mirror_push_enforcement_aspect = aspect(
    implementation = _mirror_push_enforcement_impl,
    doc = (
        "Fails analysis when an `image_push` rule targets the public mirror " +
        "surface (`{}/{}/*`) without the `{}` tag (which `mirror_push` adds).".format(
            OCI_REGISTRY,
            OCI_REPOSITORY_PREFIX,
            _MIRROR_PUSH_MANAGED_TAG,
        )
    ),
)
