load("//devtools/build/react_component:react_component.bzl", "react_component")

react_component(
    name = "CaseLog",
    srcs = ["CaseLog.tsx"],
    visibility = ["//apps/cluedo-bayes:__subpackages__"],
    deps = ["//apps/cluedo-bayes/ui/theme:tokens"],
)
