"""Bifrost Bazel macro for generating platform manifests from Starlark."""

load("@bazel_lib//lib:write_source_files.bzl", "write_source_file")
load("@bazel_skylib//rules:write_file.bzl", "write_file")

def bifrost_service(
        name,
        image,
        port,
        gcp,
        resources,
        args = None,
        service_account_name = None,
        probes = None,
        autoscaling = None,
        kubernetes = None,
        checked_in = None,
        targets = None,
        visibility = None):
    """Generate platform manifests from a Bifrost service spec defined in Starlark.

    This macro generates a Bifrost service JSON from Starlark parameters and
    runs `bifrost render` to produce Cloud Run, Kubernetes, and Terraform outputs.

    Example:
        bifrost_service(
            name = "registry",
            image = "registry",
            args = ["--upstream=ghcr.io"],
            port = 8080,
            resources = {
                "requests": {"cpu": "250m", "memory": "256Mi"},
                "limits": {"cpu": "1000m", "memory": "256Mi"},
            },
            gcp = {
                "projectId": "senku-prod",
                "cloudRun": {"region": "europe-west3"},
            },
        )

    This produces targets:
        :<name>.service.json    — generated Bifrost input spec
        :<name>.cloudrun.yaml   — Cloud Run (Knative) manifest
        :<name>.k8s.yaml        — Kubernetes manifests (SA, Deployment, HPA, Service)
        :<name>.terraform.tf    — Terraform HCL for runtime identity

    Args:
        name: Service name (used in metadata.name and as target prefix).
        image: Container image reference.
        port: Container port number.
        gcp: GCP configuration dict. Must include "projectId", "projectNumber", and
            "cloudRun" with at least "region". Example:
            {"projectId": "my-proj", "projectNumber": "123456789012", "cloudRun": {"region": "us-central1"}}.
        resources: Resource requirements dict with "requests" and/or "limits" sub-dicts,
            each containing "cpu" and "memory". Example: {"limits": {"cpu": "1000m", "memory": "256Mi"}}.
        args: Optional list of container arguments.
        service_account_name: Optional GSA email. Auto-generated from name + projectId if omitted.
        probes: Optional probe paths dict. Example: {"startupPath": "/healthz", "livenessPath": "/healthz"}.
        autoscaling: Optional autoscaling dict. Example: {"min": 0, "max": 5, "concurrency": 100}.
        kubernetes: Optional Kubernetes config dict. Example: {"namespace": "prod", "serviceType": "LoadBalancer"}.
        checked_in: Optional dict mapping render targets to checked-in output paths.
            For each mapped target, the macro creates a `write_source_file` update
            target named `:<name>_<target>_update` and adds a generated-file header
            pointing to that update command.
        targets: List of render targets to generate. Defaults to ["cloudrun", "k8s", "terraform"].
            Use this to generate only a subset of outputs.
        visibility: Bazel visibility for all generated targets.
    """
    if targets == None:
        targets = ["cloudrun", "k8s", "terraform"]
    if checked_in == None:
        checked_in = {}

    # Build the service spec dict
    spec = {}
    spec["image"] = image
    if service_account_name:
        spec["serviceAccountName"] = service_account_name
    if args:
        spec["args"] = args
    spec["port"] = port
    spec["resources"] = resources
    if probes:
        spec["probes"] = probes
    if autoscaling:
        spec["autoscaling"] = autoscaling
    spec["gcp"] = gcp
    if kubernetes != None:
        spec["kubernetes"] = kubernetes

    service_obj = {}
    service_obj["apiVersion"] = "bifrost.apotema.cloud/v1alpha1"
    service_obj["kind"] = "Service"
    service_obj["metadata"] = {"name": name}
    service_obj["spec"] = spec

    service_json = json.encode_indent(service_obj, indent = "  ") + "\n"

    json_target = name + ".service.json"
    write_file(
        name = name + "_service_json",
        out = json_target,
        content = [service_json],
        visibility = visibility,
    )

    # Generate each render target
    for target in targets:
        if target == "terraform":
            out_file = name + ".terraform.tf"
        else:
            out_file = name + "." + target + ".yaml"

        cmd = "$(execpath //bifrost/cmd/bifrost) render %s -f $(location :%s) > $@" % (
            target,
            name + "_service_json",
        )
        if target in checked_in:
            update_target = name + "_" + target + "_update"
            pkg = native.package_name()
            update_label = "//:%s" % update_target if pkg == "" else "//%s:%s" % (pkg, update_target)
            header = "\n".join([
                "# Generated by bifrost.bzl",
                "# To update this file, run:",
                "#   bazel run %s" % update_label,
                "",
            ])
            cmd = "cat <<'EOF' > $@\n%s\nEOF\n$(execpath //bifrost/cmd/bifrost) render %s -f $(location :%s) >> $@" % (
                header,
                target,
                name + "_service_json",
            )

        native.genrule(
            name = name + "_" + target,
            srcs = [":" + name + "_service_json"],
            outs = [out_file],
            cmd = cmd,
            tools = ["//bifrost/cmd/bifrost"],
            visibility = visibility,
        )

        if target in checked_in:
            write_source_file(
                name = name + "_" + target + "_update",
                in_file = ":" + name + "_" + target,
                out_file = checked_in[target],
            )
