load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "bifrost",
    srcs = ["bifrost.bzl"],
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_skylib//rules:write_file",
    ],
)
