package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"slices"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"go.yaml.in/yaml/v4"
	servingv1 "knative.dev/serving/pkg/apis/serving/v1"
)

type Options struct {
	ProjectExpr string
	Strict      bool
}

type manifestHeader struct {
	APIVersion string `yaml:"apiVersion"`
	Kind       string `yaml:"kind"`
}

type serviceAccountBinding struct {
	AccountID string
	Email     string
	Services  []string
	TFName    string
}

func ParseKnativeServices(r io.Reader) ([]servingv1.Service, error) {
	dec := yaml.NewDecoder(r)
	var services []servingv1.Service

	for {
		var node yaml.Node
		if err := dec.Decode(&node); err != nil {
			if errors.Is(err, io.EOF) {
				return services, nil
			}
			return nil, err
		}

		if len(node.Content) == 0 {
			continue
		}

		var header manifestHeader
		if err := node.Decode(&header); err != nil {
			return nil, err
		}

		if header.APIVersion != "serving.knative.dev/v1" || header.Kind != "Service" {
			continue
		}

		svc, err := decodeKnativeService(node)
		if err != nil {
			return nil, err
		}
		services = append(services, svc)
	}
}

func decodeKnativeService(node yaml.Node) (servingv1.Service, error) {
	var raw any
	if err := node.Decode(&raw); err != nil {
		return servingv1.Service{}, err
	}

	payload, err := json.Marshal(raw)
	if err != nil {
		return servingv1.Service{}, err
	}

	var svc servingv1.Service
	if err := json.Unmarshal(payload, &svc); err != nil {
		return servingv1.Service{}, err
	}

	return svc, nil
}

func GenerateTerraform(services []servingv1.Service, opts Options) (string, []string, error) {
	if len(services) == 0 {
		return "", nil, errors.New("no supported Knative Service manifests found")
	}

	projectExpr := opts.ProjectExpr
	if projectExpr == "" {
		projectExpr = "var.project_id"
	}

	bindings, warnings, err := collectBindings(services, opts.Strict)
	if err != nil {
		return "", warnings, err
	}

	var out strings.Builder
	out.WriteString("# Generated by tfgen.\n")
	out.WriteString("# This file owns supporting runtime identity only.\n")
	out.WriteString("# The Knative or Cloud Run service itself remains managed by the deploy manifest.\n\n")

	for i, binding := range bindings {
		if i > 0 {
			out.WriteString("\n")
		}
		writeServiceAccount(&out, binding, projectExpr)
	}

	return out.String(), warnings, nil
}

func collectBindings(services []servingv1.Service, strict bool) ([]serviceAccountBinding, []string, error) {
	byEmail := make(map[string]*serviceAccountBinding, len(services))

	for _, svc := range services {
		name := svc.Name
		if name == "" {
			return nil, nil, errors.New("knative service is missing metadata.name")
		}
		if len(svc.Spec.Template.Spec.Containers) == 0 {
			return nil, nil, fmt.Errorf("knative service %q has no containers", name)
		}

		email := strings.TrimSpace(svc.Spec.Template.Spec.ServiceAccountName)
		if email == "" {
			return nil, nil, fmt.Errorf("knative service %q is missing spec.template.spec.serviceAccountName", name)
		}
		if !strings.Contains(email, "@") {
			return nil, nil, fmt.Errorf("knative service %q has non-email serviceAccountName %q; Cloud Run requires a Google service account email", name, email)
		}

		accountID, err := accountIDFromEmail(email)
		if err != nil {
			return nil, nil, fmt.Errorf("knative service %q has invalid serviceAccountName %q: %w", name, email, err)
		}

		binding := byEmail[email]
		if binding == nil {
			binding = &serviceAccountBinding{
				AccountID: accountID,
				Email:     email,
				TFName:    terraformIdentifier(accountID),
			}
			byEmail[email] = binding
		}
		if !slices.Contains(binding.Services, name) {
			binding.Services = append(binding.Services, name)
		}
	}

	emails := make([]string, 0, len(byEmail))
	for email := range byEmail {
		emails = append(emails, email)
	}
	sort.Strings(emails)

	bindings := make([]serviceAccountBinding, 0, len(emails))
	var warnings []string
	for _, email := range emails {
		binding := *byEmail[email]
		sort.Strings(binding.Services)
		if len(binding.Services) > 1 {
			warning := fmt.Sprintf(
				"service account %q is referenced by multiple services: %s",
				binding.Email,
				strings.Join(binding.Services, ", "),
			)
			if strict {
				return nil, warnings, errors.New(warning)
			}
			warnings = append(warnings, warning)
		}
		bindings = append(bindings, binding)
	}

	return bindings, warnings, nil
}

func writeServiceAccount(out *strings.Builder, binding serviceAccountBinding, projectExpr string) {
	out.WriteString("# Referenced by services: ")
	out.WriteString(strings.Join(binding.Services, ", "))
	out.WriteString("\n")
	fmt.Fprintf(out, "resource \"google_service_account\" %q {\n", binding.TFName)
	writeAssignment(out, 1, "project", projectExpr)
	writeAssignment(out, 1, "account_id", strconv.Quote(binding.AccountID))
	writeAssignment(out, 1, "display_name", strconv.Quote(displayNameForServices(binding.Services, binding.AccountID)))
	out.WriteString("}\n")
}

func writeAssignment(out *strings.Builder, indent int, name, value string) {
	writeIndented(out, indent, fmt.Sprintf("%s = %s\n", name, value))
}

func writeIndented(out *strings.Builder, indent int, line string) {
	out.WriteString(strings.Repeat("  ", indent))
	out.WriteString(line)
}

func terraformIdentifier(name string) string {
	var buf bytes.Buffer
	for _, r := range name {
		switch {
		case unicode.IsLetter(r), unicode.IsDigit(r):
			buf.WriteRune(unicode.ToLower(r))
		case r == '-', r == '.', r == '/':
			buf.WriteByte('_')
		}
	}
	if buf.Len() == 0 {
		return "service"
	}
	if first := buf.String()[0]; first >= '0' && first <= '9' {
		return "service_" + buf.String()
	}
	return buf.String()
}

func accountIDFromEmail(email string) (string, error) {
	local := strings.TrimSpace(strings.SplitN(email, "@", 2)[0])
	if local == "" {
		return "", errors.New("empty account ID")
	}

	var out strings.Builder
	for _, r := range strings.ToLower(local) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out.WriteRune(r)
		case r == '-':
			out.WriteRune(r)
		}
	}

	accountID := strings.Trim(out.String(), "-")
	if accountID == "" {
		return "", errors.New("account ID must contain lowercase letters or digits")
	}
	if len(accountID) < 6 || len(accountID) > 30 {
		return "", fmt.Errorf("account ID %q must be between 6 and 30 characters", accountID)
	}
	if accountID[0] < 'a' || accountID[0] > 'z' {
		return "", fmt.Errorf("account ID %q must start with a letter", accountID)
	}
	return accountID, nil
}

func displayNameForServices(services []string, accountID string) string {
	if len(services) == 1 {
		return "Cloud Run runtime for " + services[0]
	}
	return "Cloud Run runtime for " + accountID
}
