"""Public rules for rules_rpm.

- `rpm_package`: one .rpm → (content.tar, header.blob). Generated by the
  `rpm.install` module extension for every (package, arch) in the lockfile;
  rarely instantiated by hand.
- `rpmdb_merge`: N header.blob → rpmdb.tar containing
  /usr/lib/sysimage/rpm/rpmdb.sqlite with one Packages row per input.
  Called once per image to produce the merged rpmdb layer.

Why two rules: rpmdb is binary sqlite, so per-package emission at the same
path would clobber on flatten() instead of merging. Fan-in at the layer
level is the only safe shape — see ADR 0007.
"""

load("//rpm/private:per_package.bzl", _rpm_package = "rpm_package")
load("//rpm/private:rpmdb_merge.bzl", _rpmdb_merge = "rpmdb_merge")

rpm_package = _rpm_package
rpmdb_merge = _rpmdb_merge
