"""Module extension `rpm` with one tag class: `install`.

One `install(...)` tag produces one hub repo (the `name`) plus per-package
spoke repos addressable as `@<name>//<pkg>/<arch>:content` and `:header`.
The hub repo also exposes `:pin` as a runnable target that regenerates the
lockfile from the declared package list.
"""

load("//rpm/private:install.bzl", "rpm_install_repo", "rpm_package_repo", "safe_repo_name")
load("//rpm/private:lockfile.bzl", "parse_lockfile")

_install = tag_class(
    attrs = {
        "name": attr.string(
            mandatory = True,
            doc = "Hub repo name. Consumers `use_repo(rpm, \"<name>\")` to expose it.",
        ),
        "repo_url": attr.string(
            mandatory = True,
            doc = "Base URL of the rpm repository (the directory containing repodata/).",
        ),
        "gpg_key": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "ASCII-armored PGP public key used to verify repomd.xml.asc and per-rpm signatures.",
        ),
        "architectures": attr.string_list(
            mandatory = True,
            doc = "RPM architectures to resolve. e.g. [\"x86_64\", \"aarch64\"]. \"noarch\" is implicit.",
        ),
        "packages": attr.string_list(
            mandatory = True,
            doc = "Root package names. The pin tool walks rpm:requires and writes the full transitive closure to the lockfile (same posture as @debian's apt resolver).",
        ),
        "lock_file": attr.label(
            mandatory = True,
            allow_single_file = [".json"],
            doc = "Path to the committed JSON lockfile. Regenerated by `bazel run @<name>//:pin`.",
        ),
        "purl_namespace": attr.string(
            doc = "purl namespace identifying the upstream (`pkg:rpm/<namespace>/<name>...`). Defaults to `name`. Set explicitly when consumers expect a different identity than the hub name — e.g. nginx_stable_rpm uses 'nginx.org' for grype-routable provenance.",
        ),
        "distro": attr.string(
            doc = "Consumer-side distro routing key emitted as `?distro=<value>` on every package's purl. Drives grype's per-package secdb routing — `hummingbird-1` to route to the hummingbird secdb provider, `rhel-10` for nginx.org-built RHEL10 rpms, etc. Optional; omitted from the purl when unset (which forces grype back to NVD-CPE / no-secdb matching).",
        ),
        "repomd_signature": attr.string(
            default = "required",
            values = ["required", "optional"],
            doc = "Lock-time policy for `repomd.xml.asc`. `required` (default) fails `bazel run @<name>//:pin` if the upstream returns HTTP 404 on the detached signature — the right posture for any repo that actually publishes signatures (e.g. nginx.org). `optional` warns and writes the lockfile anyway with TLS-only trust at lock time — opt-in for upstreams that don't publish a detached repomd signature (e.g. Hummingbird's RHPG, which signs each RPM individually but ships no `.asc` over repomd). A *tampered or wrong-key* signature still fails under either policy; the opt-out permits absence, not forgery.",
        ),
    },
)

def _rpm_extension_impl(mctx):
    for mod in mctx.modules:
        for install in mod.tags.install:
            lock = parse_lockfile(mctx, install.lock_file)
            lock_pkgs = lock["packages"]

            # Spoke repos: one per (package, arch) — runs rpm-extract on the rpm bytes.
            # Bazel repo names disallow `+`; sanitize only the package portion of
            # the spoke name via `safe_repo_name`. Aliases under
            # @<hub>//<pkg>/<arch> keep the original package name (Bazel package
            # paths accept `+`).
            purl_ns = install.purl_namespace or install.name
            for pkg_name, arches in lock_pkgs.items():
                for arch, entry in arches.items():
                    rpm_package_repo(
                        name = "{}__{}__{}".format(install.name, safe_repo_name(pkg_name), arch),
                        package = pkg_name,
                        arch = arch,
                        version = entry["version"],
                        url = install.repo_url.rstrip("/") + "/" + entry["path"],
                        sha256 = entry["sha256"],
                        gpg_key = install.gpg_key,
                        purl_namespace = purl_ns,
                        upstream = entry.get("upstream", ""),
                        purl_distro = install.distro,
                    )

            # Hub repo: aliases all spokes under @<name>//<pkg>/<arch>:{content,header}
            # plus a :pin target that runs the pin Go binary against the live repo.
            rpm_install_repo(
                name = install.name,
                packages = list(lock_pkgs.keys()),
                architectures = install.architectures,
                repo_url = install.repo_url,
                gpg_key = install.gpg_key,
                lock_file = install.lock_file,
                package_list = install.packages,  # roots passed through to :pin for re-resolution
                repomd_signature = install.repomd_signature,
            )

rpm = module_extension(
    implementation = _rpm_extension_impl,
    tag_classes = {"install": _install},
)
