"""Module extension `rpm` with one tag class: `install`.

One `install(...)` tag produces one hub repo (the `name`) plus per-package
spoke repos addressable as `@<name>//<pkg>/<arch>:content` and `:header`.
The hub repo also exposes `:pin` as a runnable target that regenerates the
lockfile from the declared package list.
"""

load("//rpm/private:install.bzl", "rpm_install_repo", "rpm_package_repo")
load("//rpm/private:lockfile.bzl", "parse_lockfile")

_install = tag_class(
    attrs = {
        "name": attr.string(
            mandatory = True,
            doc = "Hub repo name. Consumers `use_repo(rpm, \"<name>\")` to expose it.",
        ),
        "repo_url": attr.string(
            mandatory = True,
            doc = "Base URL of the rpm repository (the directory containing repodata/).",
        ),
        "gpg_key": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "ASCII-armored PGP public key used to verify repomd.xml.asc and per-rpm signatures.",
        ),
        "architectures": attr.string_list(
            mandatory = True,
            doc = "RPM architectures to resolve. e.g. [\"x86_64\", \"aarch64\"]. \"noarch\" is implicit.",
        ),
        "packages": attr.string_list(
            mandatory = True,
            doc = "Closed manifest of package names. The pin tool errors if any are missing upstream — no transitive auto-expansion.",
        ),
        "lock_file": attr.label(
            mandatory = True,
            allow_single_file = [".json"],
            doc = "Path to the committed JSON lockfile. Regenerated by `bazel run @<name>//:pin`.",
        ),
    },
)

def _rpm_extension_impl(mctx):
    for mod in mctx.modules:
        for install in mod.tags.install:
            lock = parse_lockfile(mctx, install.lock_file)

            # Spoke repos: one per (package, arch) — runs rpm-extract on the rpm bytes.
            for pkg_name, arches in lock["packages"].items():
                for arch, entry in arches.items():
                    rpm_package_repo(
                        name = "{}__{}__{}".format(install.name, pkg_name, arch),
                        package = pkg_name,
                        arch = arch,
                        version = entry["version"],
                        url = install.repo_url.rstrip("/") + "/" + entry["path"],
                        sha256 = entry["sha256"],
                        gpg_key = install.gpg_key,
                    )

            # Hub repo: aliases all spokes under @<name>//<pkg>/<arch>:{content,header}
            # plus a :pin target that runs the pin Go binary against the live repo.
            rpm_install_repo(
                name = install.name,
                packages = list(lock["packages"].keys()),
                architectures = install.architectures,
                repo_url = install.repo_url,
                gpg_key = install.gpg_key,
                lock_file = install.lock_file,
                package_list = install.packages,  # closed manifest passed through to :pin
            )

rpm = module_extension(
    implementation = _rpm_extension_impl,
    tag_classes = {"install": _install},
)
