load("//devtools/build/icons:icons.bzl", "app_icons")

app_icons(
    name = "icons",
    app_name = "Duelo de Espagueti",
    background_color = "#14100D",
    short_name = "Espagueti",
    svg = "icon.svg",
    theme_color = "#14100D",
    visibility = ["//apps/spaghetti-duel:__pkg__"],
)
