server {
    listen 8080;
    root /var/www/html;
    index index.html index.htm;

    client_max_body_size 2048M;

    location / {
        alias /var/www/html/;
        try_files $uri $uri/ /index.html;
    }
}
