load("//devtools/build/icons:icons.bzl", "app_icons")

app_icons(
    name = "icons",
    app_name = "Batalla de servilleta",
    background_color = "#0D211E",
    short_name = "Servilleta",
    svg = "icon.svg",
    theme_color = "#0D211E",
    visibility = ["//apps/napkin-battle:__pkg__"],
)
