load("//devtools/build/react_component:react_component.bzl", "react_component")

react_component(
    name = "Layout",
    srcs = ["Layout.tsx"],
    visibility = ["//apps/pepper-sweeper:__pkg__"],
    deps = [
        "//:node_modules/react-router",
        "//apps/pepper-sweeper/ui/theme:tokens",
    ],
)
