"""`busybox_config`: lower an intent-level config spec to a kconfig `.config`.

The output is consumed by `//busybox:codegen.bzl` as the starting `.config`
that kbuild's tooling refines via `make oldconfig`. Goal: config changes
appear as small, reviewable diffs in `BUILD.bazel` rather than as edits to a
1200-line vendored file.

kbuild parses `.config` linearly and later assignments win, so the rule
simply concatenates `base` (a starting `.config` file, if provided) with an
overlay of explicit `enable` / `disable` / `set` choices. `make oldconfig`
then fills in defaults for any symbol neither party mentions.
"""

def _busybox_config_impl(ctx):
    overlay = ctx.actions.declare_file(ctx.label.name + ".overlay")
    out = ctx.actions.declare_file(ctx.label.name)

    overrides = list(ctx.attr.enable) + list(ctx.attr.disable) + list(ctx.attr.set.keys())

    overlay_lines = ["# Generated by //busybox:config.bzl"]
    for sym in ctx.attr.enable:
        overlay_lines.append("CONFIG_%s=y" % sym)
    for sym in ctx.attr.disable:
        overlay_lines.append("# CONFIG_%s is not set" % sym)
    # `set` covers symbols that take a value (numbers, quoted strings, etc.)
    # rather than just `y`/not-set. Sorted for deterministic output.
    for sym in sorted(ctx.attr.set.keys()):
        overlay_lines.append("CONFIG_%s=%s" % (sym, ctx.attr.set[sym]))
    ctx.actions.write(overlay, "\n".join(overlay_lines) + "\n")

    if ctx.file.base:
        # busybox's kconfig parser treats the FIRST assignment of a symbol
        # as authoritative — appending an override after the base is a no-op
        # if the base already set or explicitly-unset that symbol. So strip
        # every line in the base that touches a symbol we override, then
        # concat the overlay.
        strip_regex = "^(CONFIG_(%s)=|# CONFIG_(%s) is not set$)" % (
            "|".join(overrides),
            "|".join(overrides),
        ) if overrides else "^$"
        ctx.actions.run_shell(
            inputs = [ctx.file.base, overlay],
            outputs = [out],
            command = (
                "set -eu\n" +
                'grep -vE "$1" "$2" > "$4" || true\n' +
                'cat "$3" >> "$4"\n'
            ),
            arguments = [strip_regex, ctx.file.base.path, overlay.path, out.path],
            mnemonic = "BusyboxConfig",
            progress_message = "Generating busybox .config %{label}",
        )
    else:
        ctx.actions.run_shell(
            inputs = [overlay],
            outputs = [out],
            command = 'cp "$1" "$2"',
            arguments = [overlay.path, out.path],
            mnemonic = "BusyboxConfig",
            progress_message = "Generating busybox .config %{label}",
        )

    return [DefaultInfo(files = depset([out]))]

busybox_config = rule(
    implementation = _busybox_config_impl,
    attrs = {
        "base": attr.label(
            allow_single_file = True,
            doc = "Optional starting `.config` file. Overlay is appended " +
                  "after, so overlay assignments override base ones.",
        ),
        "enable": attr.string_list(
            doc = "Symbols (without `CONFIG_` prefix) to set to `y`.",
        ),
        "disable": attr.string_list(
            doc = "Symbols explicitly disabled (emitted as " +
                  "`# CONFIG_X is not set`).",
        ),
        "set": attr.string_dict(
            doc = "Symbols set to a literal value. Use raw kconfig " +
                  "syntax: `\"y\"`, a number, or a quoted string like `'\"\"'`.",
        ),
    },
    doc = "Lower an intent-level busybox config spec into a kconfig `.config`.",
)
