# Generated by bifrost.bzl
# To update this file, run:
#   bazel run //oci/deploy:registry_terraform_update

resource "google_service_account" "svc_registry" {
  project      = "senku-prod"
  account_id   = "svc-registry"
  display_name = "Runtime identity for registry"
}
