"""Bifrost Bazel macro for generating platform manifests from Starlark."""

load("@bazel_lib//lib:write_source_files.bzl", "write_source_file")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("//devtools/bifrost:render.bzl", "bifrost_render")

def _to_camel_case(s):
    parts = s.split("_")
    return parts[0] + "".join([p.capitalize() for p in parts[1:]])

def _bifrost_workload(
        name,
        kind,
        gcp,
        resources,
        image = None,
        image_push = None,
        checked_in = None,
        targets = None,
        visibility = None,
        **kwargs):
    """Internal helper that generates platform manifests for any workload kind."""
    if image and image_push:
        fail("Cannot specify both 'image' and 'image_push'")
    if not image and not image_push:
        fail("Must specify either 'image' or 'image_push'")

    if targets == None:
        targets = ["cloudrun", "k8s", "terraform"]
    if checked_in == None:
        checked_in = {}

    spec = {"image": image or name, "resources": resources, "gcp": gcp}
    for key, value in kwargs.items():
        if value != None:
            spec[_to_camel_case(key)] = value

    workload_obj = {
        "apiVersion": "bifrost.apotema.cloud/v1alpha1",
        "kind": kind,
        "metadata": {"name": name},
        "spec": spec,
    }

    workload_json = json.encode_indent(workload_obj, indent = "  ") + "\n"

    json_target = name + ".workload.json"
    write_file(
        name = name + "_workload_json",
        out = json_target,
        content = [workload_json],
        visibility = visibility,
    )

    # Generate each render target
    for target in targets:
        if target == "terraform":
            out_file = name + ".terraform.tf"
        else:
            out_file = name + "." + target + ".yaml"

        header = ""
        if target in checked_in:
            update_target = name + "_" + target + "_update"
            pkg = native.package_name()
            update_label = "//:%s" % update_target if pkg == "" else "//%s:%s" % (pkg, update_target)
            header = "\n".join([
                "# Generated by bifrost.bzl",
                "# To update this file, run:",
                "#   bazel run %s" % update_label,
                "",
            ])

        bifrost_render(
            name = name + "_" + target,
            spec = ":" + name + "_workload_json",
            target = target,
            image_push = image_push,
            header = header if header else None,
            out = out_file,
            visibility = visibility,
        )

        if target in checked_in:
            write_source_file(
                name = name + "_" + target + "_update",
                in_file = ":" + name + "_" + target,
                out_file = checked_in[target],
            )

def bifrost_service(
        name,
        port,
        gcp,
        resources,
        image = None,
        image_push = None,
        args = None,
        service_account_name = None,
        secret_files = None,
        probes = None,
        autoscaling = None,
        kubernetes = None,
        checked_in = None,
        targets = None,
        visibility = None):
    """Generate platform manifests for a Service workload.

    Example:
        bifrost_service(
            name = "registry",
            image = "registry",
            port = 8080,
            resources = {"limits": {"cpu": "1000m", "memory": "256Mi"}},
            gcp = {"projectId": "senku-prod", "projectNumber": "874944788122", "region": "europe-west3"},
        )

    Args:
        name: Service name.
        image: Plain string container image reference. Mutually exclusive with image_push.
        image_push: Bazel label pointing to an image_push target from @rules_img.
            Mutually exclusive with image.
        port: Container port number.
        gcp: GCP configuration dict.
        resources: Resource requirements dict.
        args: Optional list of container arguments.
        service_account_name: Optional GSA email.
        secret_files: Optional list of secret file dicts.
        probes: Optional probe paths dict.
        autoscaling: Optional autoscaling dict.
        kubernetes: Optional Kubernetes config dict.
        checked_in: Optional dict mapping render targets to checked-in output paths.
        targets: List of render targets. Defaults to ["cloudrun", "k8s", "terraform"].
        visibility: Bazel visibility.
    """
    _bifrost_workload(
        name = name,
        kind = "Service",
        gcp = gcp,
        resources = resources,
        image = image,
        image_push = image_push,
        checked_in = checked_in,
        targets = targets,
        visibility = visibility,
        port = port,
        args = args,
        service_account_name = service_account_name,
        secret_files = secret_files,
        probes = probes,
        autoscaling = autoscaling,
        kubernetes = kubernetes,
    )

def bifrost_cronjob(
        name,
        schedule,
        gcp,
        resources,
        image = None,
        image_push = None,
        args = None,
        service_account_name = None,
        secret_files = None,
        job = None,
        kubernetes = None,
        checked_in = None,
        targets = None,
        visibility = None):
    """Generate platform manifests for a CronJob workload.

    Example:
        bifrost_cronjob(
            name = "analytics-data-export",
            image = "data-export",
            schedule = {"cron": "0 12 * * *", "timeZone": "Europe/Madrid"},
            resources = {"limits": {"cpu": "1000m", "memory": "512Mi"}},
            gcp = {"projectId": "senku-prod", "projectNumber": "874944788122", "region": "europe-west1"},
            kubernetes = {"namespace": "jobs"},
        )

    Args:
        name: CronJob name.
        image: Plain string container image reference. Mutually exclusive with image_push.
        image_push: Bazel label pointing to an image_push target from @rules_img.
            Mutually exclusive with image.
        schedule: Schedule dict with "cron" (required) and optional "timeZone".
        gcp: GCP configuration dict.
        resources: Resource requirements dict.
        args: Optional list of container arguments.
        service_account_name: Optional GSA email.
        secret_files: Optional list of secret file dicts.
        job: Optional job settings dict (parallelism, completions, maxRetries, timeoutSeconds).
        kubernetes: Optional Kubernetes config dict.
        checked_in: Optional dict mapping render targets to checked-in output paths.
        targets: List of render targets. Defaults to ["cloudrun", "k8s", "terraform"].
        visibility: Bazel visibility.
    """
    _bifrost_workload(
        name = name,
        kind = "CronJob",
        gcp = gcp,
        resources = resources,
        image = image,
        image_push = image_push,
        checked_in = checked_in,
        targets = targets,
        visibility = visibility,
        schedule = schedule,
        args = args,
        service_account_name = service_account_name,
        secret_files = secret_files,
        job = job,
        kubernetes = kubernetes,
    )
