load("//devtools/build/icons:icons.bzl", "app_icons")

app_icons(
    name = "icons",
    app_name = "Dino Meteoro",
    background_color = "#0C0718",
    short_name = "Dino",
    svg = "icon.svg",
    theme_color = "#0C0718",
    visibility = ["//apps/dino-meteor:__pkg__"],
)
