load("//devtools/build/icons:icons.bzl", "app_icons")

app_icons(
    name = "icons",
    app_name = "Cluedo vs. Bayes",
    background_color = "#12100E",
    short_name = "Bayes",
    svg = "icon.svg",
    theme_color = "#12100E",
    visibility = ["//apps/cluedo-bayes:__pkg__"],
)
