load("//devtools/build/react_component:react_component.bzl", "react_component")

package(default_visibility = ["//examples/stylex:__pkg__"])

react_component(
    name = "Home",
    srcs = ["Home.tsx"],
    deps = ["//examples/stylex:Button"],
)

react_component(
    name = "About",
    srcs = ["About.tsx"],
)
