load("//devtools/build/icons:icons.bzl", "app_icons")

app_icons(
    name = "icons",
    app_name = "Pimientos de Padrón",
    background_color = "#0E1113",
    short_name = "Padrón",
    svg = "icon.svg",
    theme_color = "#0E1113",
    visibility = ["//apps/pepper-sweeper:__pkg__"],
)
