load("//devtools/build/react_component:react_component.bzl", "react_component")

package(default_visibility = ["//examples/stylex:__pkg__"])

react_component(
    name = "ConcertsHome",
    srcs = ["ConcertsHome.tsx"],
    deps = ["//:node_modules/react-router"],
)

react_component(
    name = "City",
    srcs = ["City.tsx"],
    deps = ["//:node_modules/react-router"],
)

react_component(
    name = "Trending",
    srcs = ["Trending.tsx"],
)
