"""Public rules for rules_apk.

- `apk_package`: one .apk → (content.tar, installed.fragment).
  Generated by the `apk.install` module extension; rarely instantiated
  by hand.
- `apkdb_merge`: N installed-fragments → one tar containing
  /lib/apk/db/installed with concatenated records. Called once per
  image to produce the merged installed-db layer.
"""

load("//apk/private:apkdb_merge.bzl", _apkdb_merge = "apkdb_merge")
load("//apk/private:gather.bzl", _gather_apk_fragments = "gather_apk_fragments")
load("//apk/private:per_package.bzl", _apk_package = "apk_package")
load("//apk/private:providers.bzl", _ApkFragmentInfo = "ApkFragmentInfo", _TransitiveApkFragmentInfo = "TransitiveApkFragmentInfo")

apk_package = _apk_package
apkdb_merge = _apkdb_merge
gather_apk_fragments = _gather_apk_fragments
ApkFragmentInfo = _ApkFragmentInfo
TransitiveApkFragmentInfo = _TransitiveApkFragmentInfo
