"""Module extension `apk` with one tag class: `install`.

One `install(...)` tag produces one hub repo (the `name`) plus per-package
spoke repos addressable as `@<name>//<pkg>/<arch>:package`. The hub repo
also exposes `:pin` as a runnable target that regenerates the lockfile.
"""

load("//apk/private:install.bzl", "apk_install_repo", "apk_package_repo", "safe_repo_name")
load("//apk/private:lockfile.bzl", "parse_lockfile")

_install = tag_class(
    attrs = {
        "name": attr.string(
            mandatory = True,
            doc = "Hub repo name. Consumers `use_repo(apk, \"<name>\")` to expose it.",
        ),
        "repo_url": attr.string(
            mandatory = True,
            doc = "Base URL of the apk repository (the directory containing per-arch APKINDEX.tar.gz subdirs).",
        ),
        "signing_key": attr.label(
            mandatory = True,
            allow_single_file = True,
            doc = "PEM-encoded RSA public key used to verify APKINDEX.tar.gz signatures.",
        ),
        "architectures": attr.string_list(
            mandatory = True,
            doc = "APK architectures to resolve. e.g. [\"x86_64\", \"aarch64\"]. \"noarch\" is implicit.",
        ),
        "packages": attr.string_list(
            mandatory = True,
            doc = "Root package names. The pin tool walks Depends edges and writes the full transitive closure to the lockfile.",
        ),
        "lock_file": attr.label(
            mandatory = True,
            allow_single_file = [".json"],
            doc = "Path to the committed JSON lockfile. Regenerated by `bazel run @<name>//:pin`.",
        ),
        "purl_namespace": attr.string(
            doc = "purl namespace identifying the upstream (`pkg:apk/<namespace>/<name>...`). Defaults to `name`.",
        ),
        "distro": attr.string(
            doc = "Consumer-side distro routing key emitted as `?distro=<value>` on every package's purl. Drives grype's per-package secdb routing — `wolfi` for wolfi packages, `alpine-3.20` for alpine, etc.",
        ),
    },
)

def _apk_extension_impl(mctx):
    for mod in mctx.modules:
        for install in mod.tags.install:
            lock = parse_lockfile(mctx, install.lock_file)
            lock_pkgs = lock["packages"]

            purl_ns = install.purl_namespace or install.name
            for pkg_name, arches in lock_pkgs.items():
                for arch, entry in arches.items():
                    apk_package_repo(
                        name = "{}__{}__{}".format(install.name, safe_repo_name(pkg_name), arch),
                        package = pkg_name,
                        arch = arch,
                        version = entry["version"],
                        url = install.repo_url.rstrip("/") + "/" + entry["path"],
                        sha256 = entry["sha256"],
                        checksum = entry.get("checksum", ""),
                        purl_namespace = purl_ns,
                        origin = entry.get("origin", ""),
                        purl_distro = install.distro,
                    )

            apk_install_repo(
                name = install.name,
                packages = list(lock_pkgs.keys()),
                architectures = install.architectures,
                repo_url = install.repo_url,
                signing_key = install.signing_key,
                lock_file = install.lock_file,
                package_list = install.packages,
            )

apk = module_extension(
    implementation = _apk_extension_impl,
    tag_classes = {"install": _install},
)
