name: Update Grype Database
on:
  workflow_dispatch: # Allow manual trigger
  schedule:
    - cron: "0 6 * * *" # Run every day at 6AM UTC
jobs:
  update:
    uses: arkeros/senku/.github/workflows/knife-update-grype-db.yaml@main
    with:
      knife-target: //bazel/cmd/knife
      bazelrc: |
        common --config=ci
        common --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
    secrets:
      token: ${{ secrets.RENOVATE_TOKEN }}
