# Generated by bifrost.
# Supporting runtime identity for registry.

resource "google_service_account" "registry_sa" {
  project      = "senku-prod"
  account_id   = "registry-sa"
  display_name = "Runtime identity for registry"
}

resource "google_service_account_iam_member" "registry_sa_workload_identity" {
  service_account_id = google_service_account.registry_sa.name
  role               = "roles/iam.workloadIdentityUser"
  member             = "serviceAccount:senku-prod.svc.id.goog[default/registry]"
}
